// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
    public static void main(String[] args) {
        int N = Integer.parseInt(args[0]);
        double lessThan = 0;
        double greaterThan = 0;

        for (int i = 0; i < N; i++) { 
            
            double randomN = Math.random(); 
            
            if (randomN > 0.5){
                greaterThan++;
            } else {
                lessThan++;
            }
        }
        
        System.out.println("> 0.5: " + (int)greaterThan + " times");
        System.out.println("<= 0.5: " + (int)lessThan + " times");
        
        if (lessThan == 0) {
            System.out.println("Ratio: Cannot calculate (Division by Zero)"); 
        } else {
            double ratio = greaterThan / lessThan; 
            System.out.println("Ratio: " + ratio);
        }
    }
}
	
 